""" 
This is a dict mapping country names to World Bank codes
Original mapping can be found at https://wits.worldbank.org/wits/wits/witshelp/content/codes/country_codes.htm
Entries have been included where the formal name is not widely used, e.g. "Hong Kong, SAR, China" --> "Hong Kong"
"""

wb_codes = {
"Afghanistan": "AFG",
"Albania": "ALB",
"Algeria": "DZA",
"American Samoa": "ASM",
"Andorra": "AND",
"Angola": "AGO",
"Antigua": "ATG",
"Barbuda": "ATG",
"Argentina": "ARG",
"Armenia": "ARM",
"Aruba": "ABW",
"Australia": "AUS",
"Austria": "AUT",
"Azerbaijan": "AZE",
"Bahamas": "BHS",
"Bahrain": "BHR",
"Bangladesh": "BGD",
"Barbados": "BRB",
"Belarus": "BLR",
"Belgium": "BEL",
"Belize": "BLZ",
"Benin": "BEN",
"Bermuda": "BMU",
"Bhutan": "BTN",
"Bolivia": "BOL",
"Bosnia": "BIH",
"Herzegovina": "BIH",
"Botswana": "BWA",
"Brazil": "BRA",
"British Virgin Islands": "VGB",
"Brunei": "BRN",
"Bulgaria": "BGR",
"Burkina Faso": "BFA",
"Burundi": "BDI",
"Cabo Verde": "CPV",
"Cambodia": "KHM",
"Cameroon": "CMR",
"Canada": "CAN",
"Cayman Islands": "CYM",
"Central African Republic": "CAF",
"Chad": "TCD",
"Channel Islands":	"CHI",
"Chile": "CHL",
"China": "CHN",
"Colombia": "COL",
"Comoros": "COM",
"Congo":  "COD",
"Congo Rep.": "COG",
"Costa Rica":	"CRI",
"Cote d'Ivoire": "CIV",
"Croatia": "HRV",
"Cuba": "CUB",
"Curacao": "CUW",
"Cyprus": "CYP",
"Czech Republic": "CZE",
"Denmark": "DNK",
"Djibouti": "DJI",
"Dominica": "DMA",
"Dominican Republic":	"DOM",
"Ecuador": "ECU",
"Egypt Arab Rep.":	"EGY",
"Egypt":	"EGY", # Manually added
"El Salvador":	"SLV",
"Equatorial Guinea":	"GNQ",
"Eritrea": "ERI",
"Estonia": "EST",
"Ethiopia": "ETH",
"Faroe Islands":	"FRO",
"Fiji": "FJI",
"Finland": "FIN",
"France": "FRA",
"French Polynesia":	"PYF",
"Gabon": "GAB",
"The Gambia":	"GMB",
"Georgia": "GEO",
"Germany": "DEU",
"Ghana": "GHA",
"Gibraltar": "GIB",
"Greece": "GRC",
"Greenland": "GRL",
"Grenada": "GRD",
"Guam": "GUM",
"Guatemala": "GTM",
"Guinea": "GIN",
"Guinea Bissau":	"GNB",
"Guyana": "GUY",
"Haiti": "HTI",
"Honduras": "HND",
"Hong Kong SAR, China":	"HKG",
"Hong Kong":	"HKG", # Manually added
"Hungary": "HUN",
"Iceland": "ISL",
"India": "IND",
"Indonesia": "IDN",
"Iran":  	"IRN",
"Iraq": "IRQ",
"Ireland": "IRL",
"Isle of Man":	"IMN",
"Israel": "ISR",
"Italy": "ITA",
"Jamaica": "JAM",
"Japan": "JPN",
"Jordan": "JOR",
"Kazakhstan": "KAZ",
"Kenya": "KEN",
"Kiribati": "KIR",
"Dem. People's Rep. Korea":	"PRK",
"Rep. Korea":	"KOR",
"Korea":	"KOR",  # Manually added
"Kosovo": "XKX",
"Kuwait": "KWT",
"Kyrgyz Republic":	"KGZ",
"Laos": 	"LAO",
"Latvia": "LVA",
"Lebanon": "LBN",
"Lesotho": "LSO",
"Liberia": "LBR",
"Libya": "LBY",
"Liechtenstein": "LIE",
"Lithuania": "LTU",
"Luxembourg": "LUX",
"Macao": 	"MAC",
"Macedonia":  	"MKD",
"Madagascar": "MDG",
"Malawi": "MWI",
"Malaysia": "MYS",
"Maldives": "MDV",
"Mali": "MLI",
"Malta": "MLT",
"Marshall Islands":	"MHL",
"Mauritania": "MRT",
"Mauritius": "MUS",
"Mexico": "MEX",
"Micronesia": 	"FSM",
"Moldova": "MDA",
"Monaco": "MCO",
"Mongolia": "MNG",
"Montenegro": "MNE",
"Morocco": "MAR",
"Mozambique": "MOZ",
"Myanmar": "MMR",
"Namibia": "NAM",
"Nauru": "NRU",
"Nepal": "NPL",
"Netherlands": "NLD",
"New Caledonia":	"NCL",
"New Zealand":	"NZL",
"Nicaragua": "NIC",
"Niger": "NER",
"Nigeria": "NGA",
"Northern Mariana Islands":	"MNP",
"Norway": "NOR",
"Oman": "OMN",
"Pakistan": "PAK",
"Palau": "PLW",
"Panama": "PAN",
"Papua New Guinea":	"PNG",
"Paraguay": "PRY",
"Peru": "PER",
"Philippines": "PHL",
"Poland": "POL",
"Portugal": "PRT",
"Puerto Rico":	"PRI",
"Qatar": "QAT",
"Romania": "ROU",
"Russian Federation":	"RUS",
"Russia":	"RUS", # Manually added
"Rwanda": "RWA",
"Samoa": "WSM",
"San Marino":	"SMR",
"Sao Tome and Principe":	"STP",
"Saudi Arabia":	"SAU",
"Senegal": "SEN",
"Serbia": "SRB",
"Seychelles": "SYC",
"Sierra Leone":	"SLE",
"Singapore": "SGP",
"Sint Maarten":	"SXM",
"Slovak Republic":	"SVK",
"Slovenia": "SVN",
"Solomon Islands":	"SLB",
"Somalia": "SOM",
"South Africa":	"ZAF",
"South Sudan":	"SSD",
"Spain": "ESP",
"Sri Lanka":	"LKA",
"St Kitts and Nevis":	"KNA",
"St Lucia":	"LCA",
"St Martin":	"MAF",
"St Vincent and the Grenadines":	"VCT",
"Sudan": "SDN",
"Suriname": "SUR",
"Swaziland": "SWZ",
"Sweden": "SWE",
"Switzerland": "CHE",
"Syrian Arab Republic":	"SYR",
"Syria":	"SYR", # Manually added
"Taiwan":	"TWN",
"Tajikistan": "TJK",
"Tanzania": "TZA",
"Thailand": "THA",
"Timor Leste":	"TLS",
"Togo": "TGO",
"Tonga": "TON",
"Trinidad":	"TTO", # Manually added
"Tobago":	"TTO", # Manually added
"Tunisia": "TUN",
"Turkey": "TUR",
"Turkmenistan": "TKM",
"Turks":	"TCA",
"Caicos Islands":	"TCA",
"Tuvalu": "TUV",
"Uganda": "UGA",
"Ukraine": "UKR",
"United Arab Emirates":	"ARE",
"United Kingdom":	"GBR",
"United States":	"USA",
"Uruguay": "URY",
"Uzbekistan": "UZB",
"Vanuatu": "VUT",
"Venezuela": 	"VEN",
"Vietnam": "VNM",
"Virgin Islands":	"VIR",
"West Bank and Gaza":	"PSE",
"Yemen": 	"YEM",
"Zambia": "ZMB",
"Zimbabwe": "ZWE",
}
